AWSTemplateFormatVersion: '2010-09-09'
Description: HW3
Parameters:
  SageMakerEndpoint:
    Type: String
    Default: "sms-spam-classifier-mxnet-2022-12-06-18-34-10-781"


Resources:
  HW3Lambda:
    Type: AWS::Lambda::Function 
    Properties:
      Code:
        S3Bucket: codebucket-ccbd-hw3
        S3Key: Lambda.zip
      Description: Lambda function for HW3
      Tags:
        - Value: SAM
          Key: lambda:createdBy
      MemorySize: 128
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref SageMakerEndpoint
          REGION: us-east-1
      Handler: HW3Lambda.lambda_handler
      Role: arn:aws:iam::300088890034:role/service-role/LF1_2-role-n10c0i9k
      Timeout: 59
      Runtime: python3.9
      FunctionName: HW3Lambda

  EmailBucket:
    Type: AWS::S3::Bucket
    DependsOn: HW3Lambda
    Properties:
      BucketName: emailbucket-ccbd-hw3
      AccessControl: PublicReadWrite
      NotificationConfiguration: 
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt HW3Lambda.Arn
      
      PublicAccessBlockConfiguration: 
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HW3Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::emailbucket-ccbd-hw3

  SESReceiptRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'
    Properties:
      RuleSetName: 6998hw3-cloud-formation-ruleset

  ReceiptRule:
    Type: 'AWS::SES::ReceiptRule'
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: Rule1
        Actions:
          - S3Action:
              BucketName: !Ref EmailBucket
        Enabled: true
          